[[api]]
name = "Search Company"
url = "/Search/SearchCompany"
[api.headers]

[api.params]
apiVersion = "1.9"

[api.body]

[api.body.searchCompanyParameters]
taxNumber = "7838368395"

[[api]]
name = "Balance Sheets"
url = "/CompanyInformation/BalanceSheets"

[api.headers]

[api.params]
apiVersion = "1.9"

[api.body]
isWithExtendedForms = false

[api.body.period]
from = "2020-01-01T00:00:00"
to = "2024-12-25T12:21:09.2176821+03:00"

[[api]]
name = "Banks"
url = "/CompanyInformation/Banks"

[api.headers]

[api.params]
apiVersion = "1.9"

[api.body]

[[api]]
name = "Contacts"
url = "/CompanyInformation/Contacts"

[api.headers]

[api.params]
apiVersion = "1.9"

[api.body]

[[api]]
name = "Basic Information"
url = "/CompanyInformation/BasicInformation"

[api.headers]

[api.params]
apiVersion = "1.9"

[api.body]

[[api]]
name = "Certificates"
url = "/CompanyInformation/Certificates"

[api.headers]

[api.params]
apiVersion = "1.9"

[api.body]
statuses = [ "Active", "Suspended", "Canceled", "Arhive" ]
partyTypes = [ "Applicant", "Manufacturer" ]
sort = "DESC"
offset = 0
limit = 100

[[api]]
name = "Patents"
url = "/CompanyInformation/Patents"

[api.headers]

[api.params]
apiVersion = "1.9"

[api.body]
sides = [ "Inventor", "PatentHolder" ]
statuses = [ "Active", "Lapsed" ]
sort = "DESC"
offset = 0
limit = 100

[registrationDateRange]
from = "2024-01-01T00:00:00"